# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class UsersPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, email=None):  # noqa: E501
        """UsersPostRequest - a model defined in OpenAPI

        :param name: The name of this UsersPostRequest.  # noqa: E501
        :type name: str
        :param email: The email of this UsersPostRequest.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'name': str,
            'email': str
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email'
        }

        self._name = name
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'UsersPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _users_post_request of this UsersPostRequest.  # noqa: E501
        :rtype: UsersPostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this UsersPostRequest.


        :return: The name of this UsersPostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UsersPostRequest.


        :param name: The name of this UsersPostRequest.
        :type name: str
        """

        self._name = name

    @property
    def email(self):
        """Gets the email of this UsersPostRequest.


        :return: The email of this UsersPostRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UsersPostRequest.


        :param email: The email of this UsersPostRequest.
        :type email: str
        """

        self._email = email
